# SOLVCON Mesh

A mesh is a set of elements covering the space in which we want to solve for the solution of the conservation laws.  In other words, a mesh defines the geometrical domain of interests for our problem.

In [1]:
import os, sys
import pickle
import numpy as np
import solvcon as sc
from solvcon.io.core import fioregy # FIXME: this should be available in solvcon namespace.
# Load the block object.
meshpath = os.path.join(os.environ['SCSRC'], 'test', 'data', 'cubic_t200mm.g')
blk = fioregy.GenesisIO().load(stream=meshpath)
# Write out the major arrays.
names = [
    # metric.
    'ndcrd', 'fccnd', 'fcnml', 'fcara', 'clcnd', 'clvol',
    # type/meta.
    'fctpn', 'cltpn', 'clgrp',
    # connectivity.
    'fcnds', 'fccls', 'clnds', 'clfcs']
for name in names:
    arr = getattr(blk, name)
    np.save(os.path.join(name), arr)

In [2]:
print(len(blk.ndcrd))
print(blk.fcnds.min(axis=0))
print(blk.fcnds.max(axis=0))
print(np.where(blk.fcnds==316))

316
[ 3  0  0  0 -1]
[  3 315 315 315  -1]
(array([], dtype=int64), array([], dtype=int64))


In [3]:
fcnds = np.load('fcnds.npy')
print(fcnds.min(axis=0))
print(fcnds.max(axis=0))
print(np.where(fcnds==316))

[ 3  0  0  0 -1]
[  3 315 315 315  -1]
(array([], dtype=int64), array([], dtype=int64))
